name: one_dungeon
description: 1 Bit Dungeon Game
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flame: ^1.30.1
  flame_audio: ^2.11.11
  flame_behaviors: ^0.2.0
  flame_tiled: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  intl: ^0.20.2
  sharp_toggle_switch:
    path: ./packages/sharp_toggle_switch

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.0
  flame_test: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/audio/sfx/
    - assets/images/
    - assets/images/world/
    - assets/tiles/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/press_start_2p_regular.ttf
